### ISSUE TITLE
migrate all templates to jinja2

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#170]
Imported from https://projects.linaro.org/browse/QA-1739

**Comment by chaws** [comment]
Just a follow-up:

I'm half way done migrating templates to Jinja2: https://github.com/chaws/squad/tree/migrate-templates-to-jinja2

One big issue I stumbled across was Django Rest Framework's (DRF) support do Jinja2: it doesn't[1] have much.

This means that the whole /api part of the frontend will need to be handled with Django's default template engine (DTL), while the rest is being migrated to Jinja2. I managed to work around that by tweaking folders/settings a bit. Now **most** of migrated templates will be in `squad/frontend/templates/jinja2`, so that the Jinja2 engine knows that it should only look at that folder. I said most because `rest_framework/api.html` includes `squad/_user_menu.html` and both must be rendered using DTL so that /api works well with DRF. I couldn't think of anything better than keeping two copies of _user_menu: one (.[html](https://github.com/chaws/squad/blob/migrate-templates-to-jinja2/squad/frontend/templates/squad/_user_menu.html)) for `rest_framework/api.html` and another (.[jinja2](https://github.com/chaws/squad/blob/migrate-templates-to-jinja2/squad/frontend/templates/jinja2/squad/_user_menu.jinja2)) for `jinja2/squad/base.jinja2`. I'm open to suggestions.

I want to be done with this next week.

[1] https://github.com/encode/django-rest-framework/issues/4084

**Comment by mwasilew** [comment]
IIUC the only difference here is:
```
 href="{% url 'settings-home' %}"
```
vs
```
 href="{% url 'settings-home' %}"
```

Maybe it would be possible to create a block here and fill in this block differently for different engines? I guess block handling is identical for django and jinja templates. I didn't try it, so take the advice with a pinch of salt.

**Comment by chaws** [comment]
I thought about that too, but it would require checking all Django Rest Framework's templates (~70 files) and making blocks for their templates do work too. My idea here is to have 'https://qa-reports.linaro.org/api/*' using Django's template language (only because Django Rest Framework), and the rest using Jinja2. What do you think?

**Comment by chaws** [comment]
Just opened a PR #377
