### ISSUE TITLE
notification email title is misleading

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#180]
Imported from https://projects.linaro.org/browse/QA-1688
In case the build in squad contains not only pass/fail test results but also benchmarks, the title of the email notification is misleading:
erp-huawei/staging-debian: 3164 tests, 0 failed, 2872 passed (build 438-7cbef517)
Remaining results are most likely benchmarks (I didn't check the exact number). 

I think the fix for this should be removing benchmarks from the summary, so they don't count towards total number of tests. 

milosz.wasilewski:
> I guess this might be closed with custom templates in mind. The title can now be customized.

**Comment by mwasilew** [comment]
Add number of 'skip' tests to the default template.

**Comment by chaws** [comment]
The ticket was created was July/17, then @terceiro pushed the commit 
https://github.com/Linaro/squad/commit/7e954d5af75b1b6bbfdcc9d48e63196bceadbba4 in Aug/17. In Sep/17 @mwasilew commented that this might be closed due to EmailTemplate feature. Finally in Jan/18 Milosz migrated to github. I guess this is closed. I'm closing it for now since email titles are customized. Please re-open if I'm missing something
