### ISSUE TITLE
Track Known Issues

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#252]
I would like to be able to mark a failure as a known issue, and have that known issue be marked automatically on subsequent failures on the same project/environment/test suite/test name.

A table of 'known issues' that contains a url to a bug tracker and possibly other meta-data can be linked to for each known issue. 

Multiple projects can link to the same known issue.

For the time being, I don't think it should do any actual integration with a bug tracker (this could be done subsequently). Simply being able to see failures marked as known issues would improve the readability of the results enormously. It would also let us lessen our reliance on skiplists - we could simply let known tests fail because they will get marked as a known issue.

**Comment by mwasilew** [comment]
I don't think we can get rid of skip lists altogether. There will probably always be some tests that should not be executed because they cause reboot/hang/freeze of the system. This is a grave problem when executing tests from within the OS. However the list would be much shorter than it is right now.

**Comment by mwasilew** [comment]
Merged in #288 and #290
