### ISSUE TITLE
metrics: add support for marking points as outliers

### ISSUE THREAD

**Issue by terceiro** [Linaro/squad#312]
Each data point is its own object, so we can add a boolean field to it called `outlier`, and then exclude outliers (or plot them outside of the line) in the charts.

Also needs the UI for users to mark points as outliers.

**Comment by stevanradakovic** [comment]
@terceiro just to clarify, are you referring to a build here, when you say data point object?

**Comment by terceiro** [comment]
no, the actual data point that I mean is the Y value, which is the metrics. this would be marked as an outlier.  builds are the X value.

now, maybe we need to expand the data that is sent to the charts page to include the metric ID because right I thinkg we only the build date and the metric value.

**Comment by stevanradakovic** [comment]
Hm, well for the "test pass" type metric, AFAIU the point in the chart is actually the build, and for the other ones it's the metric, but all the metric results from each build will be on the horizontal line in one point in time (which represent the build in this case).

The whole point of my question is actually where should the 'outlier' field go in the model scheme? 
Having it in the metric will make it quite difficult to find the actual metric you want to make an 'outlier' unless done directly form the chart (on point click menu) like we curenlty do in LAVA.
Having it in the test run would maybe have most sense since then you can also remove this particular test run result from "Test pass %" calculation and also omit its' metrics from other chart types.

**Comment by terceiro** [comment]
if you assign the outlier flag to the testrun, then you can't know which metric collected from that test run is considered an outlier. I can have a build where most metrics are fine, but then just one is an outlier (and that is probably the most common case).

I agree that the test pass % metric makes marking individual metrics as outliers; we have two options: 1) ditch it (it was my invention, nobody ever asked for it); ot 2) only allow a point to be marked as outlier if there is a corresponding metric id in the data.

**Comment by mwasilew** [comment]
I'm in favor of option 2.
