### ISSUE TITLE
Inconsistency in environment vs environments in API

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#322]
Environments, and all list items, are referenced in the API in plural form. For example, the following url lists environments and is at /environment**s**: https://qa-reports.linaro.org/api/environments/

However, In knownissue items, environment is singular when referencing a list of environments, as can be seen at https://qa-reports.linaro.org/api/knownissues/.

**Comment by mwasilew** [comment]
That's probably our initial sin on naming the endpoints. The name in the object comes directly from the model and it's singular. I could hack it and turn into plural in the serializer, but I prefer to rename endpoints to singular if that is preferred. This will be a pretty major change, so needs to be announced with some longer lead time.

**Comment by danrue** [comment]
I thought if we could change it for knownissues it might not have much impact, but if it is going to impact the rest of the API.. I'm not sure it's a good idea to change.

**Comment by mwasilew** [comment]
@terceiro my point is there is no consistency in naming across the models. For example we have 'test_runs' and 'testruns'. Also it depends from which end you approach the object. Going from Group you get 'projects'. Coming from Build, there is 'project'. So I don't think this can be fixed in general case.

In this case I would rather rename the endpoint than the field in the model.

**Comment by terceiro** [comment]
@mwasilew ack on 'testrun' vs 'test_run'. we should probably fix that as well

however, plural or singular depends on the context. in your example, group has *projects* because a group can have multiple projects (i.e. a 1 to N relationship). a Build belongs to a single *project*, hence the singular. from Build to Project the relationship is N to 1, while it's 1 to N from Project to Build, hence project has *builds*.

in this case here, the relationship **was** wrongly named in the singular when it should be in the plural.
