### ISSUE TITLE
Revisit access rights for resubmission and outliers

### ISSUE THREAD

**Issue by stevanradakovic** [Linaro/squad#426]
From design meeting on Dec. 10th:
[milosz]
Resubmit - currently requires admin access
Mark outliers - every logged in user can do that
IMHO access should be per user (group?)/per project.

I agree with Milosz, the point is to allow both actions to users which belong to a user group which is assigned to the project group for which the operation is being requested. This method should cover it: https://github.com/Linaro/squad/blob/master/squad/core/models.py#L152

**Comment by mwasilew** [comment]
For resubmit I also think we need to define a role of 'project admin' (as a django group). So not all users that are allowed to see the project are able to resubmit jobs. Maybe we should respect 'read' and 'write' access to object type (TestJob in this case) as well as project visibility? There are a few options how this can be implemented. I don't have any preference but it is important not to affect performance.

**Comment by amrohassaan** [comment]
@mwasilew @chaws right now ability to resubmit is determined by the access level: 'submitter' in the GroupMembers table. and almost all users have this access level in prod. Changing access level to 'member' will limit certain users from abililty to resubmit. And since pr #785 default all newly created users to be members of group 'squad' they will all end up having ability to submit. Not sure exactly what needs be done here except manually changing specific users to be only 'members' in a group.

**Comment by mwasilew** [comment]
@amrohassaan as we discussed there should be 3 or maybe 4 levels of group membership (naming to be defined):
 - ordinary member: view only
 - result submitting member: can submit test/benchmark results + all ordinary member privileges
 - privileged user: can resubmit test jobs, define benchmark thresholds and create annotations + all result submitting user privileges
 - group admin: can create/delete/configure projects + all privileged user privileges

I don't think we have this implemented already. These privileges need to be done per group. Maybe for each squad group we need 4 django groups to make this happen? I'll leave the implementation details to be agreed.

**Comment by mwasilew** [comment]
Closed with #848 848
