### ISSUE TITLE
email and report API not cached when baseline is specified

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#433]
This may be intentional, but I was surprised.

When requesting a report or an email, the result is normally cached and served from cache subsequently. However, if a baseline is specified, then a new email/report is generated each time.

For example, observe the 'url' returned with the following two requests when submitted multiple times:
- https://qa-reports.linaro.org/api/builds/12017/report/?template=9&baseline=11972
- https://qa-reports.linaro.org/api/builds/12017/report/?template=9

**Comment by chaws** [comment]
Good catch @danrue !

@mwasilew I think I figured out why it's doing this. Every time there's a request as Dan mention where baseline=11972, this line https://github.com/Linaro/squad/blob/master/squad/api/rest.py#L597 will set that Build's DelayedReport Baseline to Build(pk=11972).status.

Given that, the next time the same URL is requested, line https://github.com/Linaro/squad/blob/master/squad/api/rest.py#L588 will create a new object and then save its baseline to 11972 again, thus having duplicate DelayedReport. And based on current report id and the successive requests to that URL, I bet there's lots of duplicates.

I say we replace line https://github.com/Linaro/squad/blob/master/squad/api/rest.py#L587 with 
```
try:
  baseline = Build.objects.get(pk=baseline_id).status
except:
  pass
```

so that when `delayed_report, created = self.get_object().delayed_reports.get_or_create` is called again, it won't create a new duplicated delayed report.

What do you think?

**Comment by mwasilew** [comment]
@danrue this isn't intentional. I noticed it earlier this week when fixing the 'force' and 'baseline' issues. As I didn't want to make more intrusive changes I left it as it was. I guess it was less harmful to have duplicates than to break anything. It's on my todo list for fixing today.

@chaws your proposal is a bit naive and doesn't catch the DoesNotExist error. The proper try/catch block is already there but it happens after get_or_create which triggers the bug. I'll try to refactor it in some more sensible way.
