### ISSUE TITLE
UI l10n and i18n support

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#491]
SQUAD UI should be possible to translate. Django supports translation out of the box https://docs.djangoproject.com/en/2.1/topics/i18n/translation/. It will require:
 - changes in templates
 - changes in views
 - preparing translation files.

**Comment by terceiro** [comment]
so I put together an initial implementation in #507. Example of the home page translated into Portuguese:

![Screenshot_2019-04-03 SQUAD -](https://user-images.githubusercontent.com/30027/55476690-735f5000-5641-11e9-91f9-aa8b8c0f9fff.png)

You will notice that I didn't include the pt_BR translation in the PR, because I don't think we will need it; it is just the one I was capable of doing for this proof of concept.

Also, we still need to mark strings for translation all over the place.

Do we already have people to do the actual translations?

**Comment by mwasilew** [comment]
For translation files we can use https://pootle.translatehouse.org/ and ask users for help.

**Comment by chaws** [comment]
@terceiro , @mwasilew I think we got this issue fulfilled with https://github.com/Linaro/squad/commit/189b378db94cb6d588b876c3d894fd495500cd5d and https://github.com/Linaro/squad/commit/5e361c5329c27f94bd8a740f7fcc2e8e6645d31a, do you agree?

**Comment by mwasilew** [comment]
@chaws I guess you're right. Actual translations can be tracked separately if needed.
