### ISSUE TITLE
compare projects always compares all projects in a group

### ISSUE THREAD

**Issue by terceiro** [Linaro/squad#583]
With the changes in #569 no matter which projects I choose, the comparison includes all 
projects in the group.

![cap](https://user-images.githubusercontent.com/30027/63301342-b2203a80-c2b0-11e9-9e2f-345bceb46016.gif)

**Comment by chaws** [comment]
Thanks for reporting. I wrote the correct submit function and just didn't place it in the right place. I added a fix commit to #581, (https://github.com/Linaro/squad/pull/581/commits/fff38aa484c046fa442e0f5ecc40ea37bfce6c2f), because I had to merge some code. Let me know if that's OK or if it's better to fix this in a separate PR.

**Comment by chaws** [comment]
Closed by #581
