### ISSUE TITLE
submit api should probably accept json

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#656]
The submit results API (documented at https://squad.readthedocs.io/en/latest/intro.html#result-submit-ref-label) is unnecessarily difficult to use with python's requests library for two reasons.

1. It seems to require multipart/form-data, which requests() implements with "files=".
2. It accepts a json-based testrun, but it throws the payload away.

The behavior can be demonstrated with the program below, which submits a test result using json, followed by the same data using multipart/form-data (files=).

The first submission shows up at https://staging-qa-reports.linaro.org/api/testruns/1114287/.
The second submission shows up at https://staging-qa-reports.linaro.org/api/testruns/1114288/.

It took me a while to figure this out, so I hope we can at least update the documentation with a requests() example, and investigate supporting the more native json-based payload.

```py
import json
import os
import requests
import time

url = "https://staging-qa-reports.linaro.org/api/submit/lkft/linux-stable-rc-5.5-oe/v5.5/i386"

metadata = {
    "job_id": f"{time.time()}",
    "make_kernelversion": "5.5.0",
}
log = "make output"
tests_file = {
    "build/build-arm64-gcc-9": "pass",  # or "fail"
}
headers = {
    "Auth-Token": os.environ["QA_TOKEN"],
}

result = requests.post(
    url,
    headers=headers,
    json={"metadata": metadata, "log": log, "tests_file": tests_file},
)

if not result.ok:
    print(f"Error submitting to qa-reports: {result.reason}: {result.text}")


metadata = {
    "job_id": f"{time.time()}",
    "make_kernelversion": "5.5.0",
}
result = requests.post(
    url,
    headers=headers,
    files={
        "tests": json.dumps(tests_file),
        "metadata": json.dumps(metadata),
        "log": json.dumps(log),
    },
)

if not result.ok:
    print(f"Error submitting to qa-reports: {result.reason}: {result.text}")
```

**Comment by chaws** [comment]
I just realized that we hit a but with that exact URL:

> TypeError at /api/submit/lkft/linux-stable-rc-5.5-oe/v5.5/i386
> argument of type 'float' is not iterable

I'll investigate that, because the documentation already enforces that data should be submitted in JSON (https://squad.readthedocs.io/en/latest/intro.html#test-results):

> Test results must be posted as JSON, encoded in UTF-8. The JSON data must be a hash (an object, strictly speaking)

**Comment by chaws** [comment]
@danrue I figured out what was going on.

What qa-reports already expects to be in JSON are actually field values, NOT the entire payload content-type. Here's a snippet of code that would work successfully:

```python
result = requests.post(
    url,
    headers=headers,
    data={"metadata": json.dumps(metadata), "log": log, "tests": json.dumps(tests_file)}
)
```

Also (and that took me a bit of time to find out :smile:), you were using `tests_file` in the first submission, whereas you used `tests` in the second time. It should **always** be `tests`. I know it's confusing, but that's how it's implemented in squad, perhaps removing the `tests_file` from the api would make things clearer.

Also 2, because you used `time.time()` for job_id, some of your submissions to staging passed a float value in, causing an exception raised in [this line](https://github.com/Linaro/squad/blob/master/squad/core/tasks/__init__.py#L76). 

I opened a PR that adds the example using requests and fixes that bug related to passing float as job_id.
