### ISSUE TITLE
linux_log_parser problems

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#658]
Hi!

This job resulted in a kernel panic, but linux_log_parser did not issue a test failure. https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v5.6-rc4/testrun/1261782/

Likewise, this job https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v5.6-rc4/testrun/1261813/

On another branch, this job completed successfully and has test results, but if you look at line 756 of the LAVA job, there is a kernel WARNING which was not detected. https://qa-reports.linaro.org/lkft/linux-stable-rc-5.4-oe/build/v5.4.23/testrun/1259900/

I've verified that "linux_log_parser" plugin is enabled for both of the projects given above. Could you verify the functionality of the plugin?

cc @nareshkamboju

**Comment by chaws** [comment]
That's a bit tricky... I've looked LAVA's log for this [test job](https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v5.6-rc4/testrun/1261782/) and retrieving plain log https://lkft.validation.linaro.org/scheduler/job/1261782/log_file/plain gets me only the first line of the `kernel-panic`. Same happened in https://qa-reports.linaro.org/lkft/linux-mainline-oe/build/v5.6-rc4/testrun/1261813/.

Apparently LAVA halts before printing the second line of the kernel-panic right after it matched the pattern `Kernel panic - (.*) end Kernel panic`. Also, it looks like there's a bug in LAVA because it reports that kernel-panic into a log with lvl=exception twice.

I can update linux-log-parser to consider kernel-panic as just one line then?

**Comment by danrue** [comment]
@nareshkamboju please take a look at this when you're available.

**Comment by nareshkamboju** [comment]
@chaws It would be great to get full kernel panic log.
Untill LAVA fix is available, please update linux-log-parser to consider kernel-panic in one line.
I have to file a LAVA ticket for this case.

I think you are considering Kernel WARNING, BUG and PANIC cases for linux-log-parser.

**Comment by nareshkamboju** [comment]
@chaws any update on this issue ?

**Comment by chaws** [comment]
Ok, sorry taking this long, but now it's fixed, for real...

These are the errors for missing kernel-panic and warnings logs:
![Screenshot from 2020-04-09 16-49-39](https://user-images.githubusercontent.com/2254825/78935035-5cd4ab80-7a82-11ea-9a51-c50ac5c52ed6.png)


And these for missing bugs:
![Screenshot from 2020-04-09 16-17-46](https://user-images.githubusercontent.com/2254825/78935136-84c40f00-7a82-11ea-915a-7ee170d62838.png)
