### ISSUE TITLE
UI: add 'next' and 'previous' build buttons

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#746]
UI should contain buttons/links to navigate builds without using build list. This feature is meant for single build view only.

**Comment by chaws** [comment]
Good idea, what do you think of the main Project page display the latest build by default? 

The latest build metadata is already there anyways, we might as well present its test results/metrics right away instead of "Latest Builds" . What do you think?

The user can already get a list of builds by clicking "Builds" tab already...

**Comment by mwasilew** [comment]
I'm not sure. A bit too counter intuitive IMHO. Project page would (almost) be no different from build page.
