### ISSUE TITLE
Support custom tags in gerrit plugin

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#867]
Currently gerrit plugin can only post Code-Review tags. This is a request to support custom tags. Tags should be possible to modify on the project level so it's probably best if the custom tag is defined in project settings.

**Comment by chaws** [comment]
I'm looking at Gerrit documentation https://gerrit-review.googlesource.com/Documentation/config-labels.html#label_Code-Review

I guess the names we want are "custom labels" rather than "custom tags". I'm also assuming that every new custom label a gerrit server/project has, it'll become an actual option in gerrit? 

Ex:
```
[label Code-Review]
```
enables the command `gerrit review --code-review`, therefore, I'm assuming:
```
[label My-New-Label]
```
enables `gerrit review --my-new-label`

I haven't found anything in docs that confirm my assumption, I'm going to experiment it with a local version of Gerrit then I'll land a PR with code changes.

**Comment by mwasilew** [comment]
I think you're correct. Gerrit config I found earlier contains exactly that.

**Comment by chaws** [comment]
Ok, I'm still configuring a local gerrit server so I can say for sure if that works out. I also saw in docs something like `gerrit review --label my-label=+1`, I need to confirm which is the correct one

**Comment by chaws** [comment]
Ok, the way to go is to use `--label`, which also works for built-in labels `Code-Review` and `Verified`. I'll work up on the PR and open it here soon
