### ISSUE TITLE
build next-20210212 baseline seems incorrect

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad#966]
https://qa-reports.linaro.org/api/builds/58859/

This build (`next-20210212`) listed it's baseline build as (`next-20210112`). This seems incorrect to me since there were several builds between the two.

**Comment by chaws** [comment]
Yeah, this looks weird indeed. Unfortunately it's a bit harder to fix this problem and here's why:

1. https://github.com/Linaro/squad/blob/master/squad/core/models.py#L1159, `previous_build` is retrieved when a build comparison is requested, usually when it's finished.
1.1. The problem here is that the builds before `next-20210212` and after `next-20210112` might not have been finished by the time `previous_build` of `next-20210212` was queried, thus making the baseline point to `next-20210112`
2. I say it's tricky because it's been a long-running issue in SQUAD: determining if a build is finished
2.1. There are several reasons why a build is not in `finished` state:
* not all test-jobs are completed
* some test jobs failed and it wasn't replaced by a working one
* the number of expected testjobs per environment hasn't been reached (this is more rare, but still a reason)

**Comment by chaws** [comment]
@jscook2345 did you see that pattern again recently? 

I'm about to implement something that I think will fix behaves like that. I think it's the similar to what happened here: https://github.com/Linaro/squad/issues/975

**Comment by jscook2345** [comment]
I have not seen it, but I haven't been actively looking for it. Thanks for the update!
