### ISSUE TITLE
Disable "resubmit" button of jobs that already got resubmitted

### ISSUE THREAD

**Issue by chaws** [Linaro/squad#997]
YongQin finds it confusing to have the "resubmit" option for jobs that already got resubmitted, specially if multiple re-submissions are needed.

**Comment by liuyq** [comment]
Hi, @chaws,
like for job1, either it's resubmitted by SQUAD automatically or resubmitted manually from webpage or api,  we will get a new job 2, in this time, we would like to have the "resubmit" button for job 1 disabled.
and more further, if the job 2 gets resubmitted and get a new job of job 3 for some reason, then the resubmit for job2 should be disabled too, and only job 3 could be resubmitted.

And in the output of api call, like here: https://qa-reports.linaro.org/api/testjobs/5337877/, 
would like to have some some flag to indicate if the job is a parent job, so that we would know if the result for these jobs should be ignored easily.

**Comment by liuyq** [comment]
remember @mrchapp has some concerns on this "disabling the resubmit" feature?
